[build]
command = "npm install && npm run build"
publish = "build"

[[redirects]]
from = "/api/*"
to = "https://example.backend.com/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
